name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  version:
    name: Run GitVersion
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.gitversion.outputs.SemVer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.1.1
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v1.1.1
        with:
          useConfigFile: true
      - name: Output Version
        run: |
          echo "### Version" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**${{ steps.gitversion.outputs.SemVer }}**" >> $GITHUB_STEP_SUMMARY
      
  build-docker-image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: [version]
    env:
      image-name-and-tag: nbmoody/kontroller-api:${{ needs.version.outputs.semver }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          push: false # TODO: set true when ready
          file: src/Kontroller.API/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: nbmoody/kontroller-api:latest,${{ env.image-name-and-tag }}
      - name: Output Image
        run: |
          echo "### Image Built" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**${{ env.image-name-and-tag }}**" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.build-and-push.outputs.metadata }} >> $GITHUB_STEP_SUMMARY